name: Builds

on:
  push:
    branches:
        - "**"
    paths-ignore:
        - "**.md"

jobs:
  skip_duplicates:
    name: Skip Duplicate Runs
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "same_content"
          do_not_skip: '["push", "workflow_dispatch", "schedule"]'

  windows:
    needs: skip_duplicates
    if: ${{ needs.skip_duplicates.outputs.should_skip != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Netplay]
        include:
          - build_type: Netplay
            artifact_name: windows-netplay
            build_config: Release
    env:
      DXSDK_DIR: "C:\\Program Files (x86)\\Microsoft DirectX SDK (June 2010)\\"
    name: "Windows ${{ matrix.build_type }}"
    runs-on: windows-2019
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Go"
        uses: actions/setup-go@v2
        if: matrix.build_type == 'Netplay'
      - name: "Remove Redistributable"
        shell: cmd
        run: |
          MsiExec.exe /passive /X{F0C3E5D1-1ADE-321E-8167-68EF0DE699A5}
          MsiExec.exe /passive /X{1D8E6291-B0D5-35EC-8441-6616F567A0F7}
          mkdir .\Tools\DX
      - name: "Setup MSBuild"
        uses: microsoft/setup-msbuild@v1
      - name: Cache DXSDK_Jun10.exe
        uses: actions/cache@v2
        with:
          path: ./Tools/DX/
          key: ${{ runner.os }}
      - name: "Download DirectX SDK"
        working-directory: ${{ github.workspace }}
        shell: powershell
        run: |
          if (!(Test-Path ".\Tools\DX\DXSDK_Jun10.exe" -PathType Leaf)) { Invoke-WebRequest -Uri https://github.com/project-slippi/Ishiiruka/releases/download/v2.2.5/DXSDK_Jun10.exe -UseBasicParsing -OutFile ".\Tools\DX\DXSDK_Jun10.exe" }
      - name: "Install DirectX SDK"
        working-directory: ${{ github.workspace }}
        shell: cmd
        run: |
          .\Tools\DX\DXSDK_Jun10.exe /U /F
      - name: 'Fetch Git Tags'
        shell: bash
        if: success()
        run: |
          git fetch --prune --unshallow
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "CURR_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: 'Init submodules'
        working-directory: ${{ github.workspace }}
        shell: bash
        if: success()
        run: git submodule update --init
      - name: "Build ${{ matrix.build_type }} Dolphin"
        shell: cmd
        run: |
          msbuild /p:Configuration=${{ matrix.build_config }} /p:Platform=x64 /p:USE_ANALYTICS=0 ${{ github.workspace }}\Source\dolphin-emu.sln
      #- name: "Build Netplay Updater"
      #  working-directory: ${{ github.workspace }}
      #  shell: cmd
      #  if: matrix.build_type == 'Netplay'
      #  run: |
      #    cd %GOPATH%
      #    git clone https://github.com/project-slippi/dolphin-slippi-tools
      #    cd dolphin-slippi-tools
      #    go get github.com/gonutz/w32 github.com/machinebox/graphql golang.org/x/sys/windows/registry
      #    go build
      #    copy /b /v /y dolphin-slippi-tools.exe ${{ github.workspace }}\Binary\x64\
      - name: "Prepare Artifact"
        working-directory: ${{ github.workspace }}
        run: |
          Xcopy /Y /E /I .\Data\Sys .\Binary\x64\Sys
          cd .\Binary\x64\
          fsutil file createnew FIX-VCRUNTIME140-ERROR.txt 0
          echo "Download and install this: https://aka.ms/vs/16/release/vc_redist.x64.exe" > .\FIX-VCRUNTIME140-ERROR.txt
      - name: Package Artifact
        working-directory: ${{ github.workspace }}
        run: |
          $FILE_NAME="${{ env.CURR_DATE }}-${{ env.GIT_HASH }}-${{ env.GIT_TAG }}-${{ matrix.artifact_name }}.zip"
          mkdir artifact
          cd .\Binary\x64\
          fsutil file createnew portable.txt 0
          7z a $FILE_NAME .\*
          move $FILE_NAME ..\..\artifact\
      - name: "Publish"
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.artifact_name }}
          path: "./artifact/"

  linux:
    needs: skip_duplicates
    if: ${{ needs.skip_duplicates.outputs.should_skip != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [scon]
        include:
          - build_type: scon
            artifact_name: linux
    name: "Ubuntu ${{ matrix.build_type }}"
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Fetch Git Tags'
        if: success()
        run: |
          git fetch --prune --unshallow
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "CURR_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: "Install prerequisites"
        if: success()
        shell: bash
        run: |
          sudo dpkg --add-architecture amd64
          sudo apt update
          sudo apt install \
          cmake \
          pkg-config \
          git \
          wget \
          libao-dev \
          libasound2-dev \
          libavcodec-dev \
          libavformat-dev \
          libbluetooth-dev \
          libenet-dev \
          libgtk2.0-dev \
          liblzo2-dev \
          libminiupnpc-dev \
          libopenal-dev \
          libpulse-dev \
          libreadline-dev \
          libsfml-dev \
          libsoil-dev \
          libsoundtouch-dev \
          libswscale-dev \
          libusb-1.0-0-dev \
          libwebkit2gtk-4.0-dev \
          libxext-dev \
          libxrandr-dev \
          portaudio19-dev \
          zlib1g-dev \
          libudev-dev \
          libevdev-dev \
          libmbedtls-dev \
          libcurl4-openssl-dev \
          libegl1-mesa-dev \
          libpng-dev \
          qtbase5-private-dev \
          libxxf86vm-dev \
          x11proto-xinerama-dev
      - name: "Build ${{ matrix.build_type }} Dolphin"
        if: success()
        working-directory: ${{ github.workspace }}
        run: |
          ./build-linux.sh
      - name: "Build ${{ matrix.build_type }} AppImage"
        if: success()
        working-directory: ${{ github.workspace }}
        run: |
          chmod +x ./build-appimage.sh
          ./build-appimage.sh
      - name: "Package"
        if: success()
        working-directory: ${{ github.workspace }}
        run: |
          mkdir artifact
          FILE_NAME=${{ env.CURR_DATE }}-${{ env.GIT_HASH }}-${{ env.GIT_TAG }}-${{ matrix.artifact_name }}.zip
          chmod +x ./*.AppImage
          zip -r -j "${FILE_NAME}" ./*.AppImage*
          pushd ./AppDir/usr/bin/
          zip -r -u "../../../${FILE_NAME}" ./Sys
          popd
          mv "${FILE_NAME}" ./artifact/
      - name: "Publish"
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.artifact_name }}
          path: "./artifact/"

  macOS:
    needs: skip_duplicates
    if: ${{ needs.skip_duplicates.outputs.should_skip != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [scon]
        include:
          - build_type: scon
            artifact_name: macOS
    name: "macOS ${{ matrix.build_type }}"
    runs-on: macos-10.15
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Fetch Git Tags'
        if: success()
        run: |
          git fetch --prune --unshallow
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "CURR_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: "Install 10.14 SDK"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.14.sdk.tar.xz
          tar -xf MacOSX10.14.sdk.tar.xz
          rm MacOSX10.14.sdk.tar.xz
          sudo mv MacOSX10.14.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
      - name: "Download and Install prerequisites"
        if: success()
        shell: bash
        run: |
          rm '/usr/local/bin/2to3' || true
          echo "HOMEBREW_NO_AUTO_UPDATE=1" >> $GITHUB_ENV
          brew upgrade cmake
          brew install \
          ffmpeg@2.8 \
          libpng \
          libav \
          pkgconfig \
          libao \
          sound-touch \
          hidapi \
          qt@5
      - name: "Build ${{ matrix.build_type }} Dolphin"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          CERTIFICATE_MACOS_APPLICATION: ${{ secrets.CERTIFICATE_MACOS_APPLICATION }}
        run: |
          export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib
          export LDFLAGS="-L/usr/local/opt/qt@5/lib"
          export CPPFLAGS="-I/usr/local/opt/qt@5/include"
          #chmod +x ./build-mac.sh && ./build-mac.sh ${{ matrix.build_config }}
          mkdir -p build/x86_64/Binaries/Dolphin.app
          cd build
          python3 ../BuildMacOSUniversalBinary.py ${{ matrix.build_config }} #--x86_64_qt5_path $(brew --prefix qt@5) --x86_64_cmake_prefix $(brew --prefix)
          mkdir ../artifact
          FILE_NAME=${{ env.CURR_DATE }}-${{ env.GIT_HASH }}-${{ env.GIT_TAG }}-${{ matrix.artifact_name }}
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
      - name: "Package Release DMG"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          CERTIFICATE_MACOS_APPLICATION: ${{ secrets.CERTIFICATE_MACOS_APPLICATION }}
        run: |
          chmod +x Tools/create-dmg/run.sh
          ./Tools/create-dmg/run.sh --no-internet-enable \
            --volname "SCON Dolphin Installer" \
            --volicon "Data/Dolphin.icns" \
            --background "Data/dolphin-emu.png" \
            --text-size 14 \
            --window-pos 200 120 \
            --window-size 590 610 \
            --icon-size 100 \
            --app-drop-link 440 196 \
            --icon "SCON Dolphin.app" 140 196 \
            --hide-extension "SCON Dolphin.app" \
            "${{ env.FILE_NAME }}.dmg" \
            "./build/Binaries/"
          mv "${{ env.FILE_NAME }}.dmg" artifact/
      - name: "Codesign ${{ matrix.build_type}} Dolphin"
        if: success() && env.CERTIFICATE_MACOS_APPLICATION != null
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          CERTIFICATE_MACOS_APPLICATION: ${{ secrets.CERTIFICATE_MACOS_APPLICATION }}
          CERTIFICATE_MACOS_PASSWORD: ${{ secrets.CERTIFICATE_MACOS_PASSWORD }}
        run: |
          chmod +x Tools/load-macos-certs-ci.sh && ./Tools/load-macos-certs-ci.sh
          mkdir -p ~/private_keys/
          echo '${{ secrets.APPLE_CONNECT_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
          /usr/bin/codesign -f -s "${{ secrets.APPLE_IDENTITY_HASH }}" --deep --options runtime --entitlements Source/Core/DolphinWX/Entitlements.plist ./build/Binaries/Slippi\ Dolphin.app
      - name: "Package, Sign and Notarize Netplay Release DMG"
        if: success() && env.CERTIFICATE_MACOS_APPLICATION != null
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          CERTIFICATE_MACOS_APPLICATION: ${{ secrets.CERTIFICATE_MACOS_APPLICATION }}
        run: |
          rm build/Binaries/traversal_server
          chmod +x Tools/create-dmg/run.sh
          ./Tools/create-dmg/run.sh --no-internet-enable \
            --volname "SCON Dolphin Installer" \
            --volicon "Data/Dolphin.icns" \
            --background "Data/dolphin-emu.png" \
            --text-size 14 \
            --window-pos 200 120 \
            --window-size 590 610 \
            --icon-size 100 \
            --app-drop-link 440 196 \
            --icon "SCON Dolphin.app" 140 196 \
            --hide-extension "SCON Dolphin.app" \
            "${{ env.FILE_NAME }}.dmg" \
            "./build/Binaries/"
          mv "${{ env.FILE_NAME }}.dmg" artifact/
          /usr/bin/codesign -f -s "${{ secrets.APPLE_IDENTITY_HASH }}" --deep --options runtime ./artifact/${{ env.FILE_NAME }}.dmg
          chmod +x Tools/notarize_netplay.sh && ./Tools/notarize_netplay.sh ./artifact/${{ env.FILE_NAME }}.dmg
      - name: "Publish"
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.artifact_name }}
          path: "./artifact/"

