name: Upload Latest Artifacts to Release

on:
  release:
    types: [released]

jobs:
  package:
    name: Release New SCON Dolphin
    runs-on: ubuntu-latest
    steps:
      - name: 'Get version'
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | cut -d "v" -f 2)" >> $GITHUB_ENV
      - name: Download latest artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          branch: scon-dolphin
      - name: Organize release files"
        run: |
          rm -rf *playback*
          find ./ -mindepth 2 -type f -exec mv -t ./ -i '{}' +
          find . -type d -empty -delete
          unzip *linux* && rm *linux* && rm -rf Sys # && mv Dolphin_SCON4-x86_64.AppImage "Dolphin_SCON4-x86_64.AppImage" #"scon-dolphin-${{ env.VERSION }}-Linux.zip"
          mkdir -p ${{ env.VERSION }}
          mv *.dmg "scon-dolphin-${{ env.VERSION }}-Mac.dmg"
          ls
          env
          mv *windows* "scon-dolphin-${{ env.VERSION }}-Win.zip"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

